# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.0.0

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.1
    settings:
      { optimizer: { runs: 200, enabled: true, details: { yul: false } } }
    remappings:
      - "@openzeppelin-contracts=OpenZeppelin/openzeppelin-contracts@4.0.0/contracts/"

dotenv: .env

reports:
  exclude_contracts:
    - SafeMath
