networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.1
    settings:
      { optimizer: { runs: 200, enabled: true, details: { yul: false } } }
    remappings:
      - "@openzeppelin-contracts=OpenZeppelin/openzeppelin-contracts@4.1.0/contracts/"

dotenv: .env

reports:
  exclude_contracts:
    - SafeMath

wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}
